### ISSUE TITLE
Hi, can you share the file ms3_time.csv?

### ISSUE THREAD

**Issue by heyuanpengpku** [jinxiang-liu/UFE-AVS#1]
Great work! 
The dataloader requires cfg.ANNO_CSV_TIME, but the corresponding file is missing according to the setting of the config.py. Can you please share the file? 
Thanks a lot!

**Comment by jinxiang-liu** [comment]
> Great work! The dataloader requires cfg.ANNO_CSV_TIME, but the corresponding file is missing according to the setting of the config.py. Can you please share the file? Thanks a lot!

I suppose it is a typo, please use the /data/MS/ms3_meta_data.csv file  via the [onedrive link](https://1drv.ms/f/s!Al8pv4sl4wmymoMu4tl6fNW-T4jwRg?e=XEwiTg)

**Comment by KOLE-LE** [comment]
What about the s4_semi_meta_data.csv file?
It is also a typo or can you share the file please?
Thans!

**Comment by jinxiang-liu** [comment]
> What about the s4_semi_meta_data.csv file? It is also a typo or can you share the file please? Thans!
`s4_semi_meta_data.csv` is under this folder
https://github.com/jinxiang-liu/UFE-AVS/tree/main/TPAVI/S4/meta_data

**Comment by jinxiang-liu** [comment]
> Great work! The dataloader requires cfg.ANNO_CSV_TIME, but the corresponding file is missing according to the setting of the config.py. Can you please share the file? Thanks a lot!

ms3_time.csv for AVSegFormer with UFE is here.
[ms3_time.csv](https://github.com/user-attachments/files/16472141/ms3_time.csv)

**Comment by jinxiang-liu** [comment]
ms3_time.csv for AVSegFormer with UFE is here.


[ms3_time.csv](https://github.com/user-attachments/files/16472172/ms3_time.csv)

**Comment by jinxiang-liu** [comment]
`ms3_time.csv` for AVSegFormer with UFE is here.
[ms3_time.csv](https://github.com/user-attachments/files/16472175/ms3_time.csv)
